version: 2

models:
  - name: dim_songs
    description: "Songs table"
    columns:
      - name: played_at_ct
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_genres
    description: "Genres table"
    columns:
      - name: artist_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: fct_listening_activity
    description: "User's listening activity"
    columns:
      - name: played_at
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: fct_listening_activity_trends
    description: "Day-over-day and week-over-week change in total listening time (song_duration_mins)"
    columns:
      - name: (granularity || period_start_date)
        description: "The primary key for this table"
        tests:
          - unique
          - not_null